spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 580000
    username: ${DB_USER}
    password: ${DB_PASS}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

aws:
  s3:
    bucket: ${S3_BUCKET}
    base-image-url: ${S3_BASE_URL}
  accessKey: ${AWS_ACCESS}
  secretKey: ${AWS_SECRET}

modakcut:
  name: ${LOG_NAME}
  file:
    path: ${LOG_PATH}
  size: ${LOG_SIZE}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error